version: "3"

services:
  app:
    image: app
    build: .
    volumes:
      - .:/usr/app
    depends_on:
      - postgres-db
    ports:
      - 3000:3000
    command: sh -c "yarn deploy && yarn dev"

  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: senha123
    ports:
      - 5432:5432
