version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres-db
    ports:
      - 3000:3000
    command: sh -c "yarn deploy && yarn dev"

  studio:
    build: .
    depends_on:
      - postgres-db
    ports:
      - 5556:5556
    command: yarn studio

  nginx:
    image: nginx
    ports:
        - 80:80
    depends_on:
      - studio
      - app

  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: senha123
    ports:
      - 5432:5432
